### ISSUE TITLE
Introduction to Product Development class

### ISSUE THREAD

**Issue by jueyang** [jueyang/manage-your-product#2]
Hey all,

Hope you are having a great end of the semester. I'm sending this note early since I won't be on campus for two weeks when the summer starts. Here's everything you need to know so that we can kickstart the class on time.
## What is this class about?

Read the links on the main page: https://github.com/jueyang/manage-your-product. It tells you most things you need to know about this class to get started.

I will periodically add or update these links. Will keep you posted.
## Get on Slack

Please fill out this [form](https://jue.typeform.com/to/s37Qjb) so that I can send you a Slack invite. **We will minimize the use of email for this class.**
## What you need to send me by June 2nd

Once you joined Slack, you can send me via direct message the following:
1. A description of your envisioned product based on your 5/19 presentation
   - what have you done already?
2. Your plan of carrying it out.

I will set up a time to chat or correspond with you individually during the first week of class to help you further your idea (and help make the scope of your product managable.) Detailed next actions will be sent out next week.

If you are ambitious, remember your constraints:
1. There’re a total of 11 weeks.
2. The actual time spent on building out your product is 5-7 weeks, depending on your final scope.
3. You have two and a half people on your team: yourself, one developer, and me (I’m the half since I am teaching. My develop/design time will be limited.)

The take-away: start small and concise.
## See you tomorrow

I will be at your presentations on Tuesday, 5/19, to know more about what you have worked on. Feel free to chat with me afterwards. In fact, I encourage you to do so!

@sfdevlin
@BurgosNY
@riogringa
@JuliaJRH
@sihemsf
@jwasserman
@adrieleparker
@emily-goldblum
@ericalucia
@DeronDalton
@lmechegaray
@aaronsimon
@BetsyBagel
@cristinafurlong

**Comment by jueyang** [comment]
Hey all, just a reminder to fill out the typeform so that I can add you to Slack. Please do so before June 2st and send me the above info via direct message on Slack.

I'll give you individual feedback/chat with you remotely the first week. 

https://jue.typeform.com/to/s37Qjb

Readings for first week will be posted in Slack as well.

**Comment by lmechegaray** [comment]
Hi Jue!

Filled it all and I'm all set on slack. 

Just making sure I didn't do any mistakes.

Thanks! 

Luis M 

Luis Miguel Echegaray 

Luis Miguel Echegaray
T - 917 929 9565
E - lmechegaray@yahoo.com

https://vimeo.com/119883933

**Comment by Emily-Goldblum** [comment]
Hi Jue,

Hope you're having a good week. I just filled out the form on typeform -
the next steps are you adding me to Slack right?

Best,
Emily

On Tue, May 26, 2015 at 12:57 PM, jue notifications@github.com wrote:

> Hey all, just a reminder to fill out the typeform so that I can add you to
> Slack. Please do so before June 2st and send me the above info via direct
> message on Slack.
> 
> I'll give you individual feedback/chat with you remotely the first week.
> 
> https://jue.typeform.com/to/s37Qjb
> 
> Readings for first week will be posted in Slack as well.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jueyang/manage-your-product/issues/2#issuecomment-105601920
> .

## 

Social Journalist
CUNY Graduate School of Journalism, M.A. Candidate in Social Journalism
City College of New York Alumnus, BA in Media Communications
C: 631 827 5022
Twitter: @emilygoldblum https://twitter.com/emilygoldblum
LinkedIn: https://www.linkedin.com/in/emilygoldblum

**Comment by jueyang** [comment]
Yes. For those of you who have filled the typeform, you will receive a Slack invite in your preferred email.

So far I've got 7 responses (a few of you left!) Thanks.

**Comment by jueyang** [comment]
1st session was done a while ago. Closing.
